---
services:

  api:
    networks:
      - api-network
      - redis-network
    build: .
    command: /bin/sh -c "yarn && yarn migrate:test && yarn start:dev"
    container_name: resonate-api
    environment:
      - NODE_ENV=test
    depends_on:
      - redis
      - pgsql
    ports:
      - "4000:4000"
    restart: always
    volumes:
      - ./:/var/www/api
      - ./data/media/incoming:/data/media/incoming
      - ./data/media/audio:/data/media/audio
      - ./data/media/images:/data/media/images

  pgsql:
    image: postgres:14-alpine
    env_file:
      - .env
    volumes:
      - ./data/pgsql-test:/var/lib/postgresql/data
      - ./data/pgsql-test-backups:/backups
    container_name: resonate-pgsql-test
    networks:
      api-network:
        aliases:
          - pgsql
    ports:
      - '${POSTGRES_TEST_LOCAL_MACHINE_PORT}:5432'

version: "3.7"
