name: Deploy to Production
on: [workflow_dispatch]
jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HETZNER_PROD_IP_SERVER }}
          username: ${{ secrets.HETZNER_PROD_SERVER_USER}}
          key: ${{ secrets.HETZNER_PROD_SERVER_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            cd api
            git pull
            docker-compose up --no-deps -d --force-recreate api
            docker-compose up --no-deps -d --force-recreate background
