name: Lint primarily with standard
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - name: Install our packages
        run: yarn install

      - name: Lint
        run: yarn lint
